  
language: r
sudo: false
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - R_CHECK_ARGS="--no-manual"
    - R_BUILD_ARGS="--no-manual"

branches:
  only:
  - master
  - develop
